/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_NULL = 2,
  sym_comment = 3,
  anon_sym_add = 4,
  anon_sym_and = 5,
  anon_sym_not = 6,
  anon_sym_jmp = 7,
  anon_sym_ret = 8,
  anon_sym_jsr = 9,
  anon_sym_jsrr = 10,
  anon_sym_lea = 11,
  anon_sym_ld = 12,
  anon_sym_st = 13,
  anon_sym_ldi = 14,
  anon_sym_sti = 15,
  anon_sym_ldr = 16,
  anon_sym_str = 17,
  anon_sym_br = 18,
  anon_sym_brn = 19,
  anon_sym_brz = 20,
  anon_sym_brp = 21,
  anon_sym_brnz = 22,
  anon_sym_brzp = 23,
  anon_sym_brnp = 24,
  anon_sym_brnzp = 25,
  anon_sym_trap = 26,
  anon_sym_push = 27,
  anon_sym_pop = 28,
  anon_sym_call = 29,
  anon_sym_rets = 30,
  anon_sym_rti = 31,
  sym_label = 32,
  sym_trap_alias = 33,
  sym_directive_name = 34,
  sym_register = 35,
  aux_sym_integer_token1 = 36,
  aux_sym_integer_token2 = 37,
  aux_sym_integer_token3 = 38,
  sym_string = 39,
  sym_period = 40,
  sym_comma = 41,
  sym_colon = 42,
  sym_document = 43,
  sym_line = 44,
  sym_label_definition = 45,
  sym_instruction = 46,
  sym_operand = 47,
  sym_directive = 48,
  sym_mnemonic = 49,
  sym_integer = 50,
  aux_sym_document_repeat1 = 51,
  aux_sym_instruction_repeat1 = 52,
  aux_sym_directive_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_NULL] = "\0",
  [sym_comment] = "comment",
  [anon_sym_add] = "add",
  [anon_sym_and] = "and",
  [anon_sym_not] = "not",
  [anon_sym_jmp] = "jmp",
  [anon_sym_ret] = "ret",
  [anon_sym_jsr] = "jsr",
  [anon_sym_jsrr] = "jsrr",
  [anon_sym_lea] = "lea",
  [anon_sym_ld] = "ld",
  [anon_sym_st] = "st",
  [anon_sym_ldi] = "ldi",
  [anon_sym_sti] = "sti",
  [anon_sym_ldr] = "ldr",
  [anon_sym_str] = "str",
  [anon_sym_br] = "br",
  [anon_sym_brn] = "brn",
  [anon_sym_brz] = "brz",
  [anon_sym_brp] = "brp",
  [anon_sym_brnz] = "brnz",
  [anon_sym_brzp] = "brzp",
  [anon_sym_brnp] = "brnp",
  [anon_sym_brnzp] = "brnzp",
  [anon_sym_trap] = "trap",
  [anon_sym_push] = "push",
  [anon_sym_pop] = "pop",
  [anon_sym_call] = "call",
  [anon_sym_rets] = "rets",
  [anon_sym_rti] = "rti",
  [sym_label] = "label",
  [sym_trap_alias] = "trap_alias",
  [sym_directive_name] = "directive_name",
  [sym_register] = "register",
  [aux_sym_integer_token1] = "integer_token1",
  [aux_sym_integer_token2] = "integer_token2",
  [aux_sym_integer_token3] = "integer_token3",
  [sym_string] = "string",
  [sym_period] = "period",
  [sym_comma] = "comma",
  [sym_colon] = "colon",
  [sym_document] = "document",
  [sym_line] = "line",
  [sym_label_definition] = "label_definition",
  [sym_instruction] = "instruction",
  [sym_operand] = "operand",
  [sym_directive] = "directive",
  [sym_mnemonic] = "mnemonic",
  [sym_integer] = "integer",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
  [aux_sym_directive_repeat1] = "directive_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_NULL] = anon_sym_NULL,
  [sym_comment] = sym_comment,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_jmp] = anon_sym_jmp,
  [anon_sym_ret] = anon_sym_ret,
  [anon_sym_jsr] = anon_sym_jsr,
  [anon_sym_jsrr] = anon_sym_jsrr,
  [anon_sym_lea] = anon_sym_lea,
  [anon_sym_ld] = anon_sym_ld,
  [anon_sym_st] = anon_sym_st,
  [anon_sym_ldi] = anon_sym_ldi,
  [anon_sym_sti] = anon_sym_sti,
  [anon_sym_ldr] = anon_sym_ldr,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_br] = anon_sym_br,
  [anon_sym_brn] = anon_sym_brn,
  [anon_sym_brz] = anon_sym_brz,
  [anon_sym_brp] = anon_sym_brp,
  [anon_sym_brnz] = anon_sym_brnz,
  [anon_sym_brzp] = anon_sym_brzp,
  [anon_sym_brnp] = anon_sym_brnp,
  [anon_sym_brnzp] = anon_sym_brnzp,
  [anon_sym_trap] = anon_sym_trap,
  [anon_sym_push] = anon_sym_push,
  [anon_sym_pop] = anon_sym_pop,
  [anon_sym_call] = anon_sym_call,
  [anon_sym_rets] = anon_sym_rets,
  [anon_sym_rti] = anon_sym_rti,
  [sym_label] = sym_label,
  [sym_trap_alias] = sym_trap_alias,
  [sym_directive_name] = sym_directive_name,
  [sym_register] = sym_register,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [aux_sym_integer_token2] = aux_sym_integer_token2,
  [aux_sym_integer_token3] = aux_sym_integer_token3,
  [sym_string] = sym_string,
  [sym_period] = sym_period,
  [sym_comma] = sym_comma,
  [sym_colon] = sym_colon,
  [sym_document] = sym_document,
  [sym_line] = sym_line,
  [sym_label_definition] = sym_label_definition,
  [sym_instruction] = sym_instruction,
  [sym_operand] = sym_operand,
  [sym_directive] = sym_directive,
  [sym_mnemonic] = sym_mnemonic,
  [sym_integer] = sym_integer,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
  [aux_sym_directive_repeat1] = aux_sym_directive_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jmp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ret] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jsr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jsrr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lea] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ld] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_st] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ldi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sti] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ldr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_br] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brnz] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brzp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brnp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brnzp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_push] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rets] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rti] = {
    .visible = true,
    .named = false,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_trap_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_period] = {
    .visible = true,
    .named = true,
  },
  [sym_comma] = {
    .visible = true,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_mnemonic] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 16,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        0, 17,
        '\n', 16,
        '"', 4,
        '#', 8,
        '\'', 13,
        ',', 86,
        '.', 85,
        '0', 81,
        ':', 87,
        ';', 18,
        '_', 47,
        'a', 52,
        'b', 68,
        'c', 49,
        'j', 62,
        'l', 53,
        'n', 63,
        'p', 64,
        'r', 56,
        's', 72,
        't', 70,
        'x', 75,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('d' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        0, 17,
        '\n', 16,
        '"', 4,
        '#', 8,
        '\'', 13,
        '0', 81,
        ';', 18,
        'x', 9,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(6);
      if (('1' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(82);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        0, 17,
        '\n', 16,
        '#', 8,
        '\'', 13,
        ',', 86,
        '0', 81,
        ';', 18,
        '_', 47,
        'r', 10,
        'x', 9,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        0, 17,
        '\n', 16,
        '.', 85,
        ':', 87,
        ';', 18,
        'a', 52,
        'b', 68,
        'c', 49,
        'j', 62,
        'l', 53,
        'n', 63,
        'p', 64,
        'r', 57,
        's', 72,
        't', 70,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '0') ADVANCE(81);
      if (lookahead == 'x') ADVANCE(9);
      if (('1' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(82);
      END_STATE();
    case 7:
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(78);
      END_STATE();
    case 8:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(82);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(79);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(82);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        0, 17,
        '\n', 16,
        '.', 85,
        ';', 18,
        '_', 48,
        'a', 52,
        'b', 68,
        'c', 49,
        'j', 62,
        'l', 53,
        'n', 63,
        'p', 64,
        'r', 57,
        's', 72,
        't', 70,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(14);
      if (('d' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(48);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_add);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_jmp);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_ret);
      if (lookahead == 's') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_jsr);
      if (lookahead == 'r') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_jsrr);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_lea);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_ld);
      if (lookahead == 'i') ADVANCE(29);
      if (lookahead == 'r') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_st);
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == 'r') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_ldi);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_sti);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_ldr);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_br);
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead == 'p') ADVANCE(36);
      if (lookahead == 'z') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(77);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_brn);
      if (lookahead == 'p') ADVANCE(39);
      if (lookahead == 'z') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(77);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_brz);
      if (lookahead == 'p') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_brp);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_brnz);
      if (lookahead == 'p') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_brzp);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_brnp);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_brnzp);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_trap);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_push);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_pop);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_call);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_rets);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_rti);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_label);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_label);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'a') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'a') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'a') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'd') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'd') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'd') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(77);
      if (lookahead == '8' ||
          lookahead == '9' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'h') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'i') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'l') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'l') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'm') ADVANCE(65);
      if (lookahead == 's') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'o') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'o') ADVANCE(66);
      if (lookahead == 'u') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'p') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'p') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'p') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'r') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'r') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 'r') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 't') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 't') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == 't') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_trap_alias);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_trap_alias);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_trap_alias);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_directive_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_register);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_integer_token2);
      if (lookahead == 'x') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_integer_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_integer_token3);
      if (lookahead == '\'') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_period);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_comma);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_colon);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 14},
  [3] = {.lex_state = 14},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_jmp] = ACTIONS(1),
    [anon_sym_ret] = ACTIONS(1),
    [anon_sym_jsr] = ACTIONS(1),
    [anon_sym_jsrr] = ACTIONS(1),
    [anon_sym_lea] = ACTIONS(1),
    [anon_sym_ld] = ACTIONS(1),
    [anon_sym_st] = ACTIONS(1),
    [anon_sym_ldi] = ACTIONS(1),
    [anon_sym_sti] = ACTIONS(1),
    [anon_sym_ldr] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_br] = ACTIONS(1),
    [anon_sym_brn] = ACTIONS(1),
    [anon_sym_brz] = ACTIONS(1),
    [anon_sym_brp] = ACTIONS(1),
    [anon_sym_brnz] = ACTIONS(1),
    [anon_sym_brzp] = ACTIONS(1),
    [anon_sym_brnp] = ACTIONS(1),
    [anon_sym_brnzp] = ACTIONS(1),
    [anon_sym_trap] = ACTIONS(1),
    [anon_sym_push] = ACTIONS(1),
    [anon_sym_pop] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [anon_sym_rets] = ACTIONS(1),
    [anon_sym_rti] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_trap_alias] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [aux_sym_integer_token1] = ACTIONS(1),
    [aux_sym_integer_token2] = ACTIONS(1),
    [aux_sym_integer_token3] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_period] = ACTIONS(1),
    [sym_comma] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(27),
    [sym_line] = STATE(22),
    [sym_label_definition] = STATE(4),
    [sym_instruction] = STATE(23),
    [sym_directive] = STATE(23),
    [sym_mnemonic] = STATE(12),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [anon_sym_NULL] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_add] = ACTIONS(9),
    [anon_sym_and] = ACTIONS(9),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_jmp] = ACTIONS(9),
    [anon_sym_ret] = ACTIONS(9),
    [anon_sym_jsr] = ACTIONS(9),
    [anon_sym_jsrr] = ACTIONS(9),
    [anon_sym_lea] = ACTIONS(9),
    [anon_sym_ld] = ACTIONS(9),
    [anon_sym_st] = ACTIONS(9),
    [anon_sym_ldi] = ACTIONS(9),
    [anon_sym_sti] = ACTIONS(9),
    [anon_sym_ldr] = ACTIONS(9),
    [anon_sym_str] = ACTIONS(9),
    [anon_sym_br] = ACTIONS(9),
    [anon_sym_brn] = ACTIONS(9),
    [anon_sym_brz] = ACTIONS(9),
    [anon_sym_brp] = ACTIONS(9),
    [anon_sym_brnz] = ACTIONS(9),
    [anon_sym_brzp] = ACTIONS(9),
    [anon_sym_brnp] = ACTIONS(9),
    [anon_sym_brnzp] = ACTIONS(9),
    [anon_sym_trap] = ACTIONS(9),
    [anon_sym_push] = ACTIONS(9),
    [anon_sym_pop] = ACTIONS(9),
    [anon_sym_call] = ACTIONS(9),
    [anon_sym_rets] = ACTIONS(9),
    [anon_sym_rti] = ACTIONS(9),
    [sym_label] = ACTIONS(11),
    [sym_trap_alias] = ACTIONS(13),
    [sym_period] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_line] = STATE(22),
    [sym_label_definition] = STATE(4),
    [sym_instruction] = STATE(23),
    [sym_directive] = STATE(23),
    [sym_mnemonic] = STATE(12),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LF] = ACTIONS(19),
    [anon_sym_NULL] = ACTIONS(19),
    [sym_comment] = ACTIONS(7),
    [anon_sym_add] = ACTIONS(9),
    [anon_sym_and] = ACTIONS(9),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_jmp] = ACTIONS(9),
    [anon_sym_ret] = ACTIONS(9),
    [anon_sym_jsr] = ACTIONS(9),
    [anon_sym_jsrr] = ACTIONS(9),
    [anon_sym_lea] = ACTIONS(9),
    [anon_sym_ld] = ACTIONS(9),
    [anon_sym_st] = ACTIONS(9),
    [anon_sym_ldi] = ACTIONS(9),
    [anon_sym_sti] = ACTIONS(9),
    [anon_sym_ldr] = ACTIONS(9),
    [anon_sym_str] = ACTIONS(9),
    [anon_sym_br] = ACTIONS(9),
    [anon_sym_brn] = ACTIONS(9),
    [anon_sym_brz] = ACTIONS(9),
    [anon_sym_brp] = ACTIONS(9),
    [anon_sym_brnz] = ACTIONS(9),
    [anon_sym_brzp] = ACTIONS(9),
    [anon_sym_brnp] = ACTIONS(9),
    [anon_sym_brnzp] = ACTIONS(9),
    [anon_sym_trap] = ACTIONS(9),
    [anon_sym_push] = ACTIONS(9),
    [anon_sym_pop] = ACTIONS(9),
    [anon_sym_call] = ACTIONS(9),
    [anon_sym_rets] = ACTIONS(9),
    [anon_sym_rti] = ACTIONS(9),
    [sym_label] = ACTIONS(11),
    [sym_trap_alias] = ACTIONS(13),
    [sym_period] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_line] = STATE(22),
    [sym_label_definition] = STATE(4),
    [sym_instruction] = STATE(23),
    [sym_directive] = STATE(23),
    [sym_mnemonic] = STATE(12),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(23),
    [anon_sym_NULL] = ACTIONS(23),
    [sym_comment] = ACTIONS(26),
    [anon_sym_add] = ACTIONS(29),
    [anon_sym_and] = ACTIONS(29),
    [anon_sym_not] = ACTIONS(29),
    [anon_sym_jmp] = ACTIONS(29),
    [anon_sym_ret] = ACTIONS(29),
    [anon_sym_jsr] = ACTIONS(29),
    [anon_sym_jsrr] = ACTIONS(29),
    [anon_sym_lea] = ACTIONS(29),
    [anon_sym_ld] = ACTIONS(29),
    [anon_sym_st] = ACTIONS(29),
    [anon_sym_ldi] = ACTIONS(29),
    [anon_sym_sti] = ACTIONS(29),
    [anon_sym_ldr] = ACTIONS(29),
    [anon_sym_str] = ACTIONS(29),
    [anon_sym_br] = ACTIONS(29),
    [anon_sym_brn] = ACTIONS(29),
    [anon_sym_brz] = ACTIONS(29),
    [anon_sym_brp] = ACTIONS(29),
    [anon_sym_brnz] = ACTIONS(29),
    [anon_sym_brzp] = ACTIONS(29),
    [anon_sym_brnp] = ACTIONS(29),
    [anon_sym_brnzp] = ACTIONS(29),
    [anon_sym_trap] = ACTIONS(29),
    [anon_sym_push] = ACTIONS(29),
    [anon_sym_pop] = ACTIONS(29),
    [anon_sym_call] = ACTIONS(29),
    [anon_sym_rets] = ACTIONS(29),
    [anon_sym_rti] = ACTIONS(29),
    [sym_label] = ACTIONS(32),
    [sym_trap_alias] = ACTIONS(35),
    [sym_period] = ACTIONS(38),
  },
  [STATE(4)] = {
    [sym_instruction] = STATE(24),
    [sym_directive] = STATE(24),
    [sym_mnemonic] = STATE(12),
    [anon_sym_LF] = ACTIONS(41),
    [anon_sym_NULL] = ACTIONS(41),
    [sym_comment] = ACTIONS(41),
    [anon_sym_add] = ACTIONS(9),
    [anon_sym_and] = ACTIONS(9),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_jmp] = ACTIONS(9),
    [anon_sym_ret] = ACTIONS(9),
    [anon_sym_jsr] = ACTIONS(9),
    [anon_sym_jsrr] = ACTIONS(9),
    [anon_sym_lea] = ACTIONS(9),
    [anon_sym_ld] = ACTIONS(9),
    [anon_sym_st] = ACTIONS(9),
    [anon_sym_ldi] = ACTIONS(9),
    [anon_sym_sti] = ACTIONS(9),
    [anon_sym_ldr] = ACTIONS(9),
    [anon_sym_str] = ACTIONS(9),
    [anon_sym_br] = ACTIONS(9),
    [anon_sym_brn] = ACTIONS(9),
    [anon_sym_brz] = ACTIONS(9),
    [anon_sym_brp] = ACTIONS(9),
    [anon_sym_brnz] = ACTIONS(9),
    [anon_sym_brzp] = ACTIONS(9),
    [anon_sym_brnp] = ACTIONS(9),
    [anon_sym_brnzp] = ACTIONS(9),
    [anon_sym_trap] = ACTIONS(9),
    [anon_sym_push] = ACTIONS(9),
    [anon_sym_pop] = ACTIONS(9),
    [anon_sym_call] = ACTIONS(9),
    [anon_sym_rets] = ACTIONS(9),
    [anon_sym_rti] = ACTIONS(9),
    [sym_trap_alias] = ACTIONS(43),
    [sym_period] = ACTIONS(15),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(21),
    [anon_sym_NULL] = ACTIONS(21),
    [sym_comment] = ACTIONS(21),
    [anon_sym_add] = ACTIONS(45),
    [anon_sym_and] = ACTIONS(45),
    [anon_sym_not] = ACTIONS(45),
    [anon_sym_jmp] = ACTIONS(45),
    [anon_sym_ret] = ACTIONS(45),
    [anon_sym_jsr] = ACTIONS(45),
    [anon_sym_jsrr] = ACTIONS(45),
    [anon_sym_lea] = ACTIONS(45),
    [anon_sym_ld] = ACTIONS(45),
    [anon_sym_st] = ACTIONS(45),
    [anon_sym_ldi] = ACTIONS(45),
    [anon_sym_sti] = ACTIONS(45),
    [anon_sym_ldr] = ACTIONS(45),
    [anon_sym_str] = ACTIONS(45),
    [anon_sym_br] = ACTIONS(45),
    [anon_sym_brn] = ACTIONS(45),
    [anon_sym_brz] = ACTIONS(45),
    [anon_sym_brp] = ACTIONS(45),
    [anon_sym_brnz] = ACTIONS(45),
    [anon_sym_brzp] = ACTIONS(45),
    [anon_sym_brnp] = ACTIONS(45),
    [anon_sym_brnzp] = ACTIONS(45),
    [anon_sym_trap] = ACTIONS(45),
    [anon_sym_push] = ACTIONS(45),
    [anon_sym_pop] = ACTIONS(45),
    [anon_sym_call] = ACTIONS(45),
    [anon_sym_rets] = ACTIONS(45),
    [anon_sym_rti] = ACTIONS(45),
    [sym_label] = ACTIONS(21),
    [sym_trap_alias] = ACTIONS(45),
    [sym_period] = ACTIONS(21),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_LF] = ACTIONS(47),
    [anon_sym_NULL] = ACTIONS(47),
    [sym_comment] = ACTIONS(47),
    [anon_sym_add] = ACTIONS(49),
    [anon_sym_and] = ACTIONS(49),
    [anon_sym_not] = ACTIONS(49),
    [anon_sym_jmp] = ACTIONS(49),
    [anon_sym_ret] = ACTIONS(49),
    [anon_sym_jsr] = ACTIONS(49),
    [anon_sym_jsrr] = ACTIONS(49),
    [anon_sym_lea] = ACTIONS(49),
    [anon_sym_ld] = ACTIONS(49),
    [anon_sym_st] = ACTIONS(49),
    [anon_sym_ldi] = ACTIONS(49),
    [anon_sym_sti] = ACTIONS(49),
    [anon_sym_ldr] = ACTIONS(49),
    [anon_sym_str] = ACTIONS(49),
    [anon_sym_br] = ACTIONS(49),
    [anon_sym_brn] = ACTIONS(49),
    [anon_sym_brz] = ACTIONS(49),
    [anon_sym_brp] = ACTIONS(49),
    [anon_sym_brnz] = ACTIONS(49),
    [anon_sym_brzp] = ACTIONS(49),
    [anon_sym_brnp] = ACTIONS(49),
    [anon_sym_brnzp] = ACTIONS(49),
    [anon_sym_trap] = ACTIONS(49),
    [anon_sym_push] = ACTIONS(49),
    [anon_sym_pop] = ACTIONS(49),
    [anon_sym_call] = ACTIONS(49),
    [anon_sym_rets] = ACTIONS(49),
    [anon_sym_rti] = ACTIONS(49),
    [sym_label] = ACTIONS(47),
    [sym_trap_alias] = ACTIONS(49),
    [sym_period] = ACTIONS(47),
  },
  [STATE(7)] = {
    [anon_sym_LF] = ACTIONS(51),
    [anon_sym_NULL] = ACTIONS(51),
    [sym_comment] = ACTIONS(51),
    [anon_sym_add] = ACTIONS(53),
    [anon_sym_and] = ACTIONS(53),
    [anon_sym_not] = ACTIONS(53),
    [anon_sym_jmp] = ACTIONS(53),
    [anon_sym_ret] = ACTIONS(53),
    [anon_sym_jsr] = ACTIONS(53),
    [anon_sym_jsrr] = ACTIONS(53),
    [anon_sym_lea] = ACTIONS(53),
    [anon_sym_ld] = ACTIONS(53),
    [anon_sym_st] = ACTIONS(53),
    [anon_sym_ldi] = ACTIONS(53),
    [anon_sym_sti] = ACTIONS(53),
    [anon_sym_ldr] = ACTIONS(53),
    [anon_sym_str] = ACTIONS(53),
    [anon_sym_br] = ACTIONS(53),
    [anon_sym_brn] = ACTIONS(53),
    [anon_sym_brz] = ACTIONS(53),
    [anon_sym_brp] = ACTIONS(53),
    [anon_sym_brnz] = ACTIONS(53),
    [anon_sym_brzp] = ACTIONS(53),
    [anon_sym_brnp] = ACTIONS(53),
    [anon_sym_brnzp] = ACTIONS(53),
    [anon_sym_trap] = ACTIONS(53),
    [anon_sym_push] = ACTIONS(53),
    [anon_sym_pop] = ACTIONS(53),
    [anon_sym_call] = ACTIONS(53),
    [anon_sym_rets] = ACTIONS(53),
    [anon_sym_rti] = ACTIONS(53),
    [sym_trap_alias] = ACTIONS(53),
    [sym_period] = ACTIONS(51),
    [sym_colon] = ACTIONS(55),
  },
  [STATE(8)] = {
    [anon_sym_LF] = ACTIONS(57),
    [anon_sym_NULL] = ACTIONS(57),
    [sym_comment] = ACTIONS(57),
    [anon_sym_add] = ACTIONS(59),
    [anon_sym_and] = ACTIONS(59),
    [anon_sym_not] = ACTIONS(59),
    [anon_sym_jmp] = ACTIONS(59),
    [anon_sym_ret] = ACTIONS(59),
    [anon_sym_jsr] = ACTIONS(59),
    [anon_sym_jsrr] = ACTIONS(59),
    [anon_sym_lea] = ACTIONS(59),
    [anon_sym_ld] = ACTIONS(59),
    [anon_sym_st] = ACTIONS(59),
    [anon_sym_ldi] = ACTIONS(59),
    [anon_sym_sti] = ACTIONS(59),
    [anon_sym_ldr] = ACTIONS(59),
    [anon_sym_str] = ACTIONS(59),
    [anon_sym_br] = ACTIONS(59),
    [anon_sym_brn] = ACTIONS(59),
    [anon_sym_brz] = ACTIONS(59),
    [anon_sym_brp] = ACTIONS(59),
    [anon_sym_brnz] = ACTIONS(59),
    [anon_sym_brzp] = ACTIONS(59),
    [anon_sym_brnp] = ACTIONS(59),
    [anon_sym_brnzp] = ACTIONS(59),
    [anon_sym_trap] = ACTIONS(59),
    [anon_sym_push] = ACTIONS(59),
    [anon_sym_pop] = ACTIONS(59),
    [anon_sym_call] = ACTIONS(59),
    [anon_sym_rets] = ACTIONS(59),
    [anon_sym_rti] = ACTIONS(59),
    [sym_trap_alias] = ACTIONS(59),
    [sym_period] = ACTIONS(57),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(67), 1,
      aux_sym_integer_token2,
    ACTIONS(69), 1,
      sym_comma,
    STATE(13), 1,
      sym_integer,
    ACTIONS(63), 2,
      sym_label,
      sym_register,
    ACTIONS(65), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
    STATE(10), 2,
      sym_operand,
      aux_sym_instruction_repeat1,
    ACTIONS(61), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [27] = 7,
    ACTIONS(67), 1,
      aux_sym_integer_token2,
    ACTIONS(69), 1,
      sym_comma,
    STATE(13), 1,
      sym_integer,
    ACTIONS(63), 2,
      sym_label,
      sym_register,
    ACTIONS(65), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
    STATE(11), 2,
      sym_operand,
      aux_sym_instruction_repeat1,
    ACTIONS(71), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [54] = 7,
    ACTIONS(81), 1,
      aux_sym_integer_token2,
    ACTIONS(84), 1,
      sym_comma,
    STATE(13), 1,
      sym_integer,
    ACTIONS(75), 2,
      sym_label,
      sym_register,
    ACTIONS(78), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
    STATE(11), 2,
      sym_operand,
      aux_sym_instruction_repeat1,
    ACTIONS(73), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [81] = 6,
    ACTIONS(67), 1,
      aux_sym_integer_token2,
    STATE(9), 1,
      sym_operand,
    STATE(13), 1,
      sym_integer,
    ACTIONS(63), 2,
      sym_label,
      sym_register,
    ACTIONS(65), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
    ACTIONS(87), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [104] = 2,
    ACTIONS(91), 1,
      aux_sym_integer_token2,
    ACTIONS(89), 8,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
      sym_label,
      sym_register,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
      sym_comma,
  [118] = 5,
    ACTIONS(97), 1,
      aux_sym_integer_token2,
    ACTIONS(99), 1,
      sym_string,
    ACTIONS(95), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
    STATE(17), 2,
      sym_integer,
      aux_sym_directive_repeat1,
    ACTIONS(93), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [138] = 5,
    ACTIONS(106), 1,
      aux_sym_integer_token2,
    ACTIONS(109), 1,
      sym_string,
    ACTIONS(103), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
    STATE(15), 2,
      sym_integer,
      aux_sym_directive_repeat1,
    ACTIONS(101), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [158] = 2,
    ACTIONS(114), 1,
      aux_sym_integer_token2,
    ACTIONS(112), 8,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
      sym_label,
      sym_register,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
      sym_comma,
  [172] = 5,
    ACTIONS(97), 1,
      aux_sym_integer_token2,
    ACTIONS(118), 1,
      sym_string,
    ACTIONS(95), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
    STATE(15), 2,
      sym_integer,
      aux_sym_directive_repeat1,
    ACTIONS(116), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [192] = 2,
    ACTIONS(120), 1,
      aux_sym_integer_token2,
    ACTIONS(73), 8,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
      sym_label,
      sym_register,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
      sym_comma,
  [206] = 2,
    ACTIONS(124), 1,
      aux_sym_integer_token2,
    ACTIONS(122), 7,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
      sym_label,
      sym_register,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
  [219] = 5,
    ACTIONS(67), 1,
      aux_sym_integer_token2,
    STATE(13), 1,
      sym_integer,
    STATE(18), 1,
      sym_operand,
    ACTIONS(63), 2,
      sym_label,
      sym_register,
    ACTIONS(65), 2,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
  [237] = 2,
    ACTIONS(114), 1,
      aux_sym_integer_token2,
    ACTIONS(112), 6,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
      aux_sym_integer_token1,
      aux_sym_integer_token3,
      sym_string,
  [249] = 2,
    ACTIONS(128), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_LF,
      anon_sym_NULL,
  [257] = 1,
    ACTIONS(41), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [263] = 1,
    ACTIONS(130), 3,
      anon_sym_LF,
      anon_sym_NULL,
      sym_comment,
  [269] = 1,
    ACTIONS(126), 2,
      anon_sym_LF,
      anon_sym_NULL,
  [274] = 1,
    ACTIONS(132), 2,
      anon_sym_LF,
      anon_sym_NULL,
  [279] = 1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
  [283] = 1,
    ACTIONS(136), 1,
      sym_directive_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 27,
  [SMALL_STATE(11)] = 54,
  [SMALL_STATE(12)] = 81,
  [SMALL_STATE(13)] = 104,
  [SMALL_STATE(14)] = 118,
  [SMALL_STATE(15)] = 138,
  [SMALL_STATE(16)] = 158,
  [SMALL_STATE(17)] = 172,
  [SMALL_STATE(18)] = 192,
  [SMALL_STATE(19)] = 206,
  [SMALL_STATE(20)] = 219,
  [SMALL_STATE(21)] = 237,
  [SMALL_STATE(22)] = 249,
  [SMALL_STATE(23)] = 257,
  [SMALL_STATE(24)] = 263,
  [SMALL_STATE(25)] = 269,
  [SMALL_STATE(26)] = 274,
  [SMALL_STATE(27)] = 279,
  [SMALL_STATE(28)] = 283,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_definition, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_definition, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operand, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mnemonic, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mnemonic, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [134] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lc3(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lc3",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
